### ISSUE TITLE
speak_listen error i guesss

### ISSUE THREAD

**Issue by well300** [reybahl/Assistant#8]
When I try to run this code it gives me this error, I've tried every possible outcome that I know. Even if there is no problem in my mic as well may you help me with this error 

`````````````````````````````````````````````````````````````````````````````````````````````````````
python main.py
Ready
Hotword Detected
Listening
Traceback (most recent call last):
  File "C:\Users\thinker\Downloads\Assistant-master\Assistant-master\assistant_functions\speak_listen.py", line 30, in listen
    audio = self.r.listen(source, timeout=7, phrase_time_limit=5)
  File "C:\Users\thinker\AppData\Roaming\Python\Python310\site-packages\speech_recognition\__init__.py", line 465, in listen
    assert source.stream is not None, "Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thinker\Downloads\Assistant-master\Assistant-master\main.py", line 100, in <module>
    assistant.main()
  File "C:\Users\thinker\Downloads\Assistant-master\Assistant-master\main.py", line 93, in main
    said = speak_listen.listen() #Listens for user input
  File "C:\Users\thinker\Downloads\Assistant-master\Assistant-master\assistant_functions\speak_listen.py", line 27, in listen
    with self.mic as source:
  File "C:\Users\thinker\AppData\Roaming\Python\Python310\site-packages\speech_recognition\__init__.py", line 189, in __exit__
    self.stream.close()
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by reybahl** [comment]
If you look at line 12 in `speak_listen.py`, you'll see the following code:
```
self.mic = sr.Microphone(device_index=2)
```
Try changing the `device_index` parameter — let me know if that fixes the issue.
